import { SlidersHorizontal, Fingerprint, Eye, Check } from 'lucide-react';
import DownloadCTA from '../components/DownloadCTA';
import Reveal from '../components/Reveal';
import FoundersSection from '../components/FoundersSection';
import FeedbackSection from '../components/FeedbackSection';
import SupportIDIA from '../components/SupportIDIA';
const principles = [[SlidersHorizontal, 'User Control', 'You choose what to protect and what to share. IDIA makes those decisions clearer.'], [Fingerprint, 'Privacy by Design', 'Protection belongs at the beginning of an AI interaction, before private details are shared.'], [Eye, 'Transparency', 'Show what’s detected, what changes, and where the limits are. No promises of perfect security.'], [Check, 'Practicality', 'Useful protection fits into real workflows. Keep it clear, accessible, and simple to use.']];
export default function About() {
  return <div className="page-enter about-page"><section className="container about-intro"><div className="eyebrow"><span className="eyebrow-line" />WHY WE’RE HERE</div><h1>Privacy should be built into<br />how we use <span className="headline-accent">AI.</span></h1><p>IDIA was created to give users more control over the information they share with generative AI.</p></section><FoundersSection /><section className="mission-section"><div className="container mission-content"><div className="eyebrow">OUR MISSION</div><h2>Make privacy protection simple enough to become part of everyday AI use.</h2></div></section><section className="container section about-why"><Reveal><div className="eyebrow">WHY IDIA</div><h2>Ordinary content.<br />Personal information.</h2></Reveal><Reveal><p>AI is becoming part of how we write, learn, research, and work. We share documents, images, messages, research, and work materials to get useful help.</p><p>But those everyday materials can contain private information: a name in a message, an account number in a document, or an address in an image.</p><p>IDIA creates a privacy layer before that information reaches AI systems, helping you review sensitive details and choose what should be protected.</p><div className="material-tags">{['Documents', 'Images', 'Messages', 'Research', 'Work materials'].map(item => <span key={item}>{item}</span>)}</div></Reveal></section><section className="container section about-principles"><Reveal><div className="eyebrow">OUR PRINCIPLES</div><h2>What stays at the center.</h2><div className="principles">{principles.map(([Icon, title, copy]) => <article key={title}><Icon size={23} /><h3>{title}</h3><p>{copy}</p></article>)}</div></Reveal></section><Reveal><DownloadCTA /></Reveal><FeedbackSection /><SupportIDIA /></div>;
}
